apiVersion: v1
kind: Service
metadata:
  labels:
    app: food-service-backend-svc
  name: food-service-backend-svc
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: food-service-backend

