apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: food-service-backend-deployment
  name: food-service-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-service-backend
  template:
    metadata:
      labels:
        app: food-service-backend
    spec:
      containers:
        - env:
            - name: postgre.address
              value: postgres
          image: erich852/tech-challenge
          name: tech-challenge-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 1m
      restartPolicy: Always
